#ifndef __MODULES_H__
#define __MODULES_H__

// code below is auto-generated by python script
// {Insert Below}

// System Task's process
extern void SysTask(void);
// System Idle's process
extern void SysIdle(void);
// TTY process
extern void Task_TTY(void);

#define __MODULES_COUNT__ 3
#define __MODULES_ENTRIES__ {(unsigned int)SysTask,(unsigned int)SysIdle,(unsigned int)Task_TTY}
#define __MODULES_PREFERRED_PID__ {(unsigned int)1,(unsigned int)0,(unsigned int)0xFFFFFFFE}

// {Insert Above}
// code above is auto-generated by python script

#endif // __MODULES_H__
