#ifndef __MODULES_H__
#define __MODULES_H__

#include "kernel/type.h"

// code below is auto-generated by python script
// {Insert Below}

// TTY Process
extern void Task_TTY();
#define __MODULES_COUNT__ 1
#define __MODULES_DEFINES__ {(uint)Task_TTY}

// {Insert Above}
// code above is auto-generated by python script

#endif // __MODULES_H__